<?php

/**
 * @file
 */

/**
 * Implements hook_file_chooser_field_plugins().
 */
function file_chooser_field_file_chooser_field_plugins() {
  return [
    'dropbox' => [
      'name'         => t('Dropbox JavaScript Chooser API'),
      'phpClassName' => 'DropboxChooserAPI',
    ],
    'google_drive' => [
      'name'         => t('Google Picker API'),
      'phpClassName' => 'GooglePickerAPI',
    ],
    'box' => [
      'name'         => t('Box File Picker'),
      'phpClassName' => 'BoxPickerAPI',
    ],
    'one_drive' => [
      'name'         => t('OneDrive'),
      'phpClassName' => 'OneDriveAPI',
    ],
    'example' => [
      'name'         => t('Example'),
      'phpClassName' => 'Example',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function file_chooser_field_theme() {
  return [
    'file_chooser_field' => [
      'variables' => [
        'label'      => NULL,
        'class'      => NULL,
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Preprocess function for the file-chooser-field
 */
function file_chooser_field_preprocess_file_chooser_field(&$vars) {
  if (count($vars['attributes'])) {
    foreach ($vars['attributes'] as $data => $value) {
      if ($data == "plugin") {
        $value = explode('\\', $value);
        $value = end($value);
        $data_attributes[] = ' data-' . $data . '=' . $value . '';
      }
      else {
        $data_attributes[] = ' data-' . $data . '="' . $value . '"';
      }
      $vars['data_attributes'] = join(" ", $data_attributes);
    }
  }
}

/**
 * Implements hook_library_info_build().
 */
function file_chooser_field_library_info_build() {
  $libraries = [];
  if (Drupal::moduleHandler()->moduleExists('file_chooser_field')) {
    $config = \Drupal::config('file_chooser_field.settings');

    $libraries['file_chooser_field.onedrive'] = [
      'js' => [
        'https://js.live.net/v5.0/OneDrive.js' => [
          'type' => 'external',
          'minified' => TRUE,
          'attributes' => [
            'id'        => 'onedrive-js',
            'client-id' => $config->get('onedrive_app_id'),
          ],
        ],
      ],
    ];

    $libraries['file_chooser_field.dropbox'] = [
      'js' => [
        'https://www.dropbox.com/static/api/2/dropins.js' => [
          'type' => 'external',
          'minified' => TRUE,
          'attributes' => [
            'id'           => 'dropboxjs',
            'data-app-key' => $config->get('dropbox_app_key'),
          ],
        ],
      ],
    ];
  }

  return $libraries;
}

/**
 * Implements hook_file_chooser_field_plugins_alter().
 */
function hook_file_chooser_field_plugins_alter(&$plugins) {
  // Alter File Chooser Field plugins.
}

/**
 * Implements hook_file_chooser_field_download().
 */
function hook_file_chooser_field_download($phpClassName, $remote_file, $local_file) {
  // This could be used to track file downloades.
  // @todo add better description.
}
